from enum import IntEnum

from custom_types import Address


HEADER_LENGTH = 10
WORKER_HEADER_LENGTH = 32
SERVER_HEADER_LENGTH = 32
WORKER_HEADER_MESSAGE_LENGTH = 16
SERVER_HEADER_MESSAGE_LENGTH = 17

SERVER_HOST_NAME = "server"
SERVER_PORT = 8000
SERVER_PORT_WORKERS = 8001
SERVER_ADDRESS: Address = (SERVER_HOST_NAME, SERVER_PORT)
SERVER_ADDRESS_WORKERS: Address = (SERVER_HOST_NAME, SERVER_PORT_WORKERS)


class MessageType(IntEnum):
	INITIAL_CONNECTION = 0
	INFO = 1
	WORK_RESULT = 2
	WORK_DONE = 3
	ERROR = 9


class ResponseStatus(IntEnum):
	# Success
	CONNECTION_ACCEPTED = 0
	# Exception
	CONNECTION_REFUSED = 10
	# Other
	UNKNOWN = 20


class WorkerStatus(IntEnum):
	NOT_CONNECTED = 0
	CONNECTED = 1
	WORKING = 2
	ERROR = 9
