version: "3.0"
services:

    client:
      container_name: client
      build:
        context: ./
        dockerfile: ./docker_files/client
      ports:
        - "8001:8000"
        - "2201:22"
      volumes:
        - ./:/var/client
      depends_on:
        - server

    client_0:
      container_name: client_0
      build:
        context: ./
        dockerfile: ./docker_files/client
      ports:
        - "2200:22"
      volumes:
        - ./:/var/client
      depends_on:
        - server

    server:
      container_name: server
      build:
        context: ./
        dockerfile: ./docker_files/server_compose
      ports:
        - "8002:8000"
        - "8003:8001"
        - "2202:22"
      volumes:
        - ./:/var/server

    worker:
      build:
        context: ./
        dockerfile: ./docker_files/worker
      ports:
        - "8005:8000"
      volumes:
        - ./:/var/worker
      depends_on:
        - server

    react_client:
      build:
        context: ./
        dockerfile: ./docker_files/react_client_compose
      ports:
        - "3000:3000"
        - "2203:22"
      volumes:
        - ./react_client:/var/react_client
      depends_on:
        - server

volumes:
  worker:
  client:
  server:
  react_client:
